import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import PDFDocument from 'pdfkit'

function inr(amount: number): string {
  return '₹' + amount.toLocaleString('en-IN')
}

export async function GET(req: NextRequest) {
  try {
    const sessionId = req.nextUrl.searchParams.get('sessionId')
    if (!sessionId) {
      return NextResponse.json({ error: 'sessionId is required' }, { status: 400 })
    }

    const session = await prisma.analysisSession.findUnique({
      where: { id: sessionId },
      include: {
        findings: { orderBy: { projectedAnnualWaste: 'desc' }, take: 10 },
        forecasts: { orderBy: { forecastMonth: 'asc' }, take: 3 },
      },
    })
    if (!session) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 })
    }

    const actions = await prisma.actionLog.findMany({
      where: { finding: { sessionId } },
      orderBy: { priority: 'asc' },
      take: 10,
    })

    const companyName = process.env.COMPANY_NAME ?? 'Your Company'
    const totalAnnualSavings = actions.reduce((s, a) => s + a.estimatedSavingAnnual, 0)

    // Build PDF in memory
    const buffers: Buffer[] = []
    const doc = new PDFDocument({ size: 'A4', margin: 48, info: { Title: 'Finci CFO Report', Author: 'Finci AI CFO' } })

    doc.on('data', (chunk: Buffer) => buffers.push(chunk))

    const finciTeal = '#00D4AA'
    const darkBg    = '#0A0B0E'
    const lightText = '#F0F2F5'
    const mutedText = '#8B92A5'
    const dangerRed = '#FF4D6A'

    function footer(doc: PDFKit.PDFDocument) {
      const footerY = doc.page.height - 40
      doc.fontSize(8).fillColor(mutedText)
        .text(
          `Generated by Finci AI CFO  |  finci.ai  |  ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST`,
          48,
          footerY,
          { align: 'center', width: doc.page.width - 96 },
        )
    }

    // ────── Page 1: Cover ──────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg)

    doc.fontSize(48).fillColor(finciTeal).font('Helvetica-Bold')
      .text('FINCI', 48, 160)

    doc.fontSize(18).fillColor(lightText).font('Helvetica')
      .text('Cost Intelligence Report', 48, doc.y + 8)

    doc.moveDown(1)
    doc.fontSize(13).fillColor(mutedText)
      .text(companyName, 48, doc.y)
      .text(`Generated: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`)

    // Metrics row
    const metrics = [
      { label: 'Total Spend', value: inr(session.totalSpend) },
      { label: 'Total Waste', value: inr(session.totalWaste) },
      { label: 'Overspend', value: `${session.overspendPct.toFixed(1)}%` },
      { label: 'Savings Possible', value: inr(totalAnnualSavings / 12) + '/mo' },
    ]
    const boxY = 360
    const boxW = (doc.page.width - 96 - 24) / 4
    metrics.forEach((m, i) => {
      const x = 48 + i * (boxW + 8)
      doc.rect(x, boxY, boxW, 80).fill('#111318')
      doc.fontSize(9).fillColor(mutedText).font('Helvetica')
        .text(m.label.toUpperCase(), x + 12, boxY + 12, { width: boxW - 24 })
      doc.fontSize(15).fillColor(finciTeal).font('Helvetica-Bold')
        .text(m.value, x + 12, boxY + 30, { width: boxW - 24 })
    })

    doc.fontSize(10).fillColor(mutedText).font('Helvetica')
      .text('CONFIDENTIAL', 48, doc.page.height - 100, {
        align: 'center', width: doc.page.width - 96,
        oblique: true,
      })

    footer(doc)

    // ────── Page 2: Executive Summary ─────────────────────────────────────
    doc.addPage()
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg)

    doc.fontSize(22).fillColor(finciTeal).font('Helvetica-Bold')
      .text('Executive Summary', 48, 48)
    doc.moveDown(0.5)
    doc.fontSize(13).fillColor(lightText).font('Helvetica')
      .text(
        `${companyName} is overspending ${session.overspendPct.toFixed(0)}% due to cost anomalies detected in the latest analysis period.`,
        48, doc.y, { width: doc.page.width - 96 },
      )
    doc.fontSize(13).fillColor(finciTeal).font('Helvetica-Bold')
      .text(
        `Applying top ${Math.min(actions.length, 3)} optimizations saves ${inr(totalAnnualSavings)} annually.`,
        48, doc.y + 4, { width: doc.page.width - 96 },
      )

    doc.moveDown(1.5)
    doc.fontSize(11).fillColor(mutedText).font('Helvetica')
      .text('TOP FINDINGS', 48, doc.y)
    doc.moveDown(0.5)

    // Findings table header
    const cols = [48, 220, 330, 430, 510]
    const colLabels = ['Finding', 'Baseline', 'Anomaly', 'Delta', 'Confidence']
    colLabels.forEach((label, i) => {
      doc.fontSize(8).fillColor(mutedText).text(label, cols[i], doc.y, { width: 80 })
    })
    doc.moveDown(0.3)
    doc.strokeColor('#1E2535').lineWidth(0.5)
      .moveTo(48, doc.y).lineTo(doc.page.width - 48, doc.y).stroke()
    doc.moveDown(0.3)

    session.findings.slice(0, 6).forEach((f) => {
      const rowY = doc.y
      doc.fontSize(9).fillColor(lightText).font('Helvetica')
        .text(f.title.substring(0, 26), cols[0], rowY, { width: 165 })
      doc.fillColor(mutedText)
        .text(inr(f.baselineAmount), cols[1], rowY, { width: 100 })
        .text(inr(f.anomalyAmount), cols[2], rowY, { width: 90 })
      doc.fillColor(dangerRed)
        .text(inr(f.deltaAmount), cols[3], rowY, { width: 80 })
      doc.fillColor(finciTeal)
        .text(`${(f.confidenceScore * 100).toFixed(0)}%`, cols[4], rowY, { width: 60 })
      doc.moveDown(0.6)
    })

    footer(doc)

    // ────── Page 3: Action Plan ────────────────────────────────────────────
    doc.addPage()
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg)

    doc.fontSize(22).fillColor(finciTeal).font('Helvetica-Bold')
      .text('Prioritized Action Plan', 48, 48)
    doc.moveDown(1)

    const aCols = [48, 60, 280, 380, 470]
    const aLabels = ['#', 'Action', 'Monthly', 'Annual', 'Status']
    aLabels.forEach((label, i) => {
      doc.fontSize(8).fillColor(mutedText).text(label, aCols[i], doc.y, { width: 100 })
    })
    doc.moveDown(0.4)
    doc.strokeColor('#1E2535').lineWidth(0.5)
      .moveTo(48, doc.y).lineTo(doc.page.width - 48, doc.y).stroke()
    doc.moveDown(0.4)

    actions.forEach((a) => {
      const rowY = doc.y
      doc.fontSize(9).fillColor(finciTeal).font('Helvetica-Bold')
        .text(`${a.priority}`, aCols[0], rowY, { width: 12 })
      doc.fillColor(lightText).font('Helvetica')
        .text(a.title.substring(0, 28), aCols[1], rowY, { width: 215 })
      doc.fillColor(finciTeal)
        .text(inr(a.estimatedSavingMonthly), aCols[2], rowY, { width: 90 })
        .text(inr(a.estimatedSavingAnnual), aCols[3], rowY, { width: 90 })
      doc.fillColor(a.status === 'AUTO_EXECUTED' ? finciTeal : mutedText)
        .text(a.status.replace(/_/g, ' '), aCols[4], rowY, { width: 90 })
      doc.moveDown(0.7)
    })

    doc.moveDown(0.5)
    doc.strokeColor(finciTeal).lineWidth(0.5)
      .moveTo(48, doc.y).lineTo(doc.page.width - 48, doc.y).stroke()
    doc.moveDown(0.5)
    doc.fontSize(14).fillColor(lightText).font('Helvetica')
      .text('Total annual savings if all actions applied:', 48, doc.y)
    doc.fontSize(20).fillColor(finciTeal).font('Helvetica-Bold')
      .text(inr(totalAnnualSavings), 48, doc.y + 4)

    footer(doc)

    // ────── Page 4: 30-Day Forecast ────────────────────────────────────────
    doc.addPage()
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(darkBg)

    doc.fontSize(22).fillColor(finciTeal).font('Helvetica-Bold')
      .text('30-Day Forecast & Risk Outlook', 48, 48)
    doc.moveDown(0.5)

    session.forecasts.forEach((fc, i) => {
      const isAlert = fc.isAlert
      const boxY2 = 100 + i * 90
      doc.rect(48, boxY2, doc.page.width - 96, 76).fill(isAlert ? '#1A0F12' : '#111318')
      doc.rect(48, boxY2, 3, 76).fill(isAlert ? dangerRed : finciTeal)
      doc.fontSize(9).fillColor(mutedText).font('Helvetica')
        .text(`Month ${i + 1} — ${fc.riskCategory} Risk`, 60, boxY2 + 10, { width: 200 })
      doc.fontSize(13).fillColor(isAlert ? dangerRed : lightText).font('Helvetica-Bold')
        .text(`Projected Spend: ${inr(fc.predictedSpend)}`, 60, boxY2 + 26, { width: 300 })
      doc.fontSize(9).fillColor(mutedText).font('Helvetica')
        .text(fc.alertMessage.replace(/^⚠️\s?/, ''), 60, boxY2 + 48, { width: doc.page.width - 130 })
    })

    footer(doc)

    doc.end()

    await new Promise<void>((resolve) => doc.on('end', resolve))
    const pdfBuffer = Buffer.concat(buffers)

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="finci-report-${sessionId.substring(0, 8)}.pdf"`,
        'Content-Length': pdfBuffer.length.toString(),
      },
    })
  } catch (err) {
    console.error('[export/pdf]', err)
    return NextResponse.json({ error: 'PDF generation failed' }, { status: 500 })
  }
}
