'use client'

import { useRef, useState } from 'react'

interface Props {
  score: number
  grade: string
  annualWaste: number
  totalSavings: number
  sessionDate?: string
  companyName?: string
}

export default function ShareableScoreCard({
  score,
  grade,
  annualWaste,
  totalSavings,
  sessionDate = new Date().toLocaleDateString('en-IN'),
  companyName = 'Your Company',
}: Props) {
  const [downloading, setDownloading] = useState(false)
  const canvasRef = useRef<HTMLCanvasElement>(null)

  function drawCard(): HTMLCanvasElement {
    const W = 1200, H = 630
    const canvas = document.createElement('canvas')
    canvas.width = W; canvas.height = H
    const ctx = canvas.getContext('2d')!

    // Background
    ctx.fillStyle = '#0A0B0E'
    ctx.fillRect(0, 0, W, H)

    // Dot grid
    ctx.fillStyle = 'rgba(255,255,255,0.03)'
    for (let x = 0; x < W; x += 30) {
      for (let y = 0; y < H; y += 30) {
        ctx.beginPath(); ctx.arc(x, y, 1, 0, Math.PI * 2); ctx.fill()
      }
    }

    // Left accent stripe
    const grad = ctx.createLinearGradient(0, 0, 0, H)
    grad.addColorStop(0, '#00D4AA'); grad.addColorStop(1, 'transparent')
    ctx.fillStyle = grad; ctx.fillRect(0, 0, 4, H)

    // Logo
    ctx.font = 'bold 28px "Courier New", monospace'
    ctx.fillStyle = '#00D4AA'; ctx.fillText('fi', 60, 70)
    ctx.fillStyle = '#F0F2F5'; ctx.fillText('nci', 87, 70)

    // Tag line
    ctx.font = '14px "Courier New", monospace'
    ctx.fillStyle = '#4A5065'
    ctx.fillText('AI CFO — Budget Health Report', 60, 95)

    // Score ring (using arcs)
    const cx = 900, cy = 315, R = 110
    const CIRC = 2 * Math.PI * R
    ctx.strokeStyle = '#1E2535'; ctx.lineWidth = 16
    ctx.beginPath(); ctx.arc(cx, cy, R, -Math.PI / 2, 1.5 * Math.PI); ctx.stroke()

    const scoreColor = score >= 80 ? '#00D4AA' : score >= 60 ? '#FFB547' : '#FF4D6A'
    ctx.strokeStyle = scoreColor; ctx.lineWidth = 16
    ctx.lineCap = 'round'
    ctx.beginPath()
    ctx.arc(cx, cy, R, -Math.PI / 2, -Math.PI / 2 + (score / 100) * 2 * Math.PI)
    ctx.stroke()

    ctx.font = 'bold 64px "Courier New", monospace'
    ctx.fillStyle = scoreColor; ctx.textAlign = 'center'
    ctx.fillText(String(score), cx, cy + 18)
    ctx.font = '18px "Courier New", monospace'
    ctx.fillStyle = '#8B92A5'
    ctx.fillText(`Grade: ${grade}`, cx, cy + 50)
    ctx.fillText('/ 100', cx, cy + 72)
    ctx.textAlign = 'left'

    // Metrics
    const metricsY = 220
    function drawMetric(label: string, value: string, valueColor: string, x: number) {
      ctx.font = '12px "Courier New", monospace'
      ctx.fillStyle = '#4A5065'
      ctx.fillText(label.toUpperCase(), x, metricsY)
      ctx.font = 'bold 36px "Courier New", monospace'
      ctx.fillStyle = valueColor
      ctx.fillText(value, x, metricsY + 50)
    }

    drawMetric('Annual Waste', `₹${(annualWaste / 100000).toFixed(1)}L`, '#FF4D6A', 60)
    drawMetric('Recoverable', `₹${(totalSavings / 100000).toFixed(1)}L`, '#00D4AA', 60 + 340)

    // Divider
    ctx.strokeStyle = '#1E2535'; ctx.lineWidth = 1
    ctx.beginPath(); ctx.moveTo(60, metricsY + 80); ctx.lineTo(800, metricsY + 80); ctx.stroke()

    // Company + date
    ctx.font = '16px "Courier New", monospace'
    ctx.fillStyle = '#8B92A5'
    ctx.fillText(`${companyName}  ·  Analysis dated ${sessionDate}`, 60, metricsY + 110)

    // Bottom brand strip
    ctx.fillStyle = '#0D0F14'
    ctx.fillRect(0, H - 60, W, 60)
    ctx.font = '13px "Courier New", monospace'
    ctx.fillStyle = '#4A5065'
    ctx.fillText('Generated by FINCI — AI CFO Platform  |  fincy.ai', 60, H - 20)

    return canvas
  }

  function handleDownload() {
    setDownloading(true)
    try {
      const canvas = drawCard()
      canvas.toBlob((blob) => {
        if (!blob) return
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a'); a.href = url
        a.download = `finci-score-${Date.now()}.png`; a.click()
        URL.revokeObjectURL(url)
        setDownloading(false)
      }, 'image/png')
    } catch {
      setDownloading(false)
    }
  }

  return (
    <button
      onClick={handleDownload}
      disabled={downloading}
      style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '10px 20px', background: 'rgba(0,212,170,0.1)', border: '1px solid rgba(0,212,170,0.3)', borderRadius: 10, color: '#00D4AA', fontSize: 13, cursor: downloading ? 'wait' : 'pointer', fontFamily: "'DM Mono', monospace", transition: 'all 0.2s' }}
    >
      <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
        <path d="M7.5 1v9m0 0L4 7m3.5 3L11 7" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
        <path d="M2 12h11" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
      </svg>
      {downloading ? 'Generating…' : 'Share Score Card'}
      <canvas ref={canvasRef} style={{ display: 'none' }} />
    </button>
  )
}
